<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
</head>
<body>
    <form action="" method="post">
        <div>
            <label for="language">Select a target language: </label>
            <select name="language" id="language">
                <?php foreach ($languages as $language) : ?>
                    <?php if ($language === 'English') : ?>
                <option selected="selected"><?= $language ?></option>
                    <?php else : ?>
                <option><?= $language ?></option>
                    <?php endif ?>
                <?php endforeach ?>
            </select>
        </div>
        <?php if (isset($languageFalse) && $languageFalse) : ?>
            <p>Select a language from the list</p>
        <?php endif ?>
        <div>
            <label for="word-1">Word: </label>
            <input type="text" name="word-1" id="word-1">
        </div>
        <?php if (isset($wordEmpty) && $wordEmpty) : ?>
            <p>Word is empty</p>
        <?php endif ?>
        <button>Build my deck</button>
    </form>
</body>
