<footer id="fixed-footer">
    <div class="bg-light p-3 small">
        <div class="container">
            <div class="text-center">
                Copyright © 2023
                <br>
                <a href="http://github.com/cicxjo/ankilernu">Source code</a> licenced under the
                <a href="https://www.gnu.org/licenses/agpl-3.0.html">GNU General Public License,
                    version 3.0 or later</a>
            </div>
        </div>
    </div>
</footer>
